.PHONY: all
all: test lint

include common.mk

# black reformats files.
.PHONY: black
black: configure
	poetry run black $(SRC)

.PHONY: doc
doc:
	poetry run $(MAKE) -C docs html

.PHONY: prepare-patch prepare-minor prepare-major
prepare-patch:
	poetry run python update-version.py patch
prepare-minor:
	poetry run python update-version.py minor
prepare-major:
	poetry run python update-version.py major
