.PHONY: all
all: test lint

include common.mk

.PHONY: lint
lint: black flake8

# black reformats files.
.PHONY: black
black: configure
	poetry run black $(SRC)

.PHONY: flake8
flake8: configure
	poetry run flake8 $(SRC)
